// Autogenerated from Pigeon (v3.2.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class EventRequest;
@class EventResponse;

@interface EventRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithName:(NSString *)name
    id:(NSString *)id
    type:(NSString *)type;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy) NSString * type;
@end

@interface EventResponse : NSObject
+ (instancetype)makeWithData:(nullable NSString *)data
    code:(nullable NSNumber *)code
    description:(nullable NSString *)description;
@property(nonatomic, copy, nullable) NSString * data;
@property(nonatomic, strong, nullable) NSNumber * code;
@property(nonatomic, copy, nullable) NSString * description;
@end

/// The codec used by YandexAdsApi.
NSObject<FlutterMessageCodec> *YandexAdsApiGetCodec(void);

@protocol YandexAdsApi
- (void)initializeWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)onAdLoadedRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)onAdFailedToLoadRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)onImpressionRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)onAdClickedRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)onRewardedRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)onLeftApplicationRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)onReturnedToApplicationRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)onAdShownRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)onAdDismissedRequest:(EventRequest *)request completion:(void(^)(EventResponse *_Nullable, FlutterError *_Nullable))completion;
@end

extern void YandexAdsApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<YandexAdsApi> *_Nullable api);

NS_ASSUME_NONNULL_END
